functionsDirectory = "/private/tmp/forja-labs-web/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "/private/tmp/forja-labs-web/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"
functions = "/private/tmp/forja-labs-web/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]